---
- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Install Docker Compose
  shell: |
    ARCH=$(uname -m)
    OS=$(uname -s)
    curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-${OS}-${ARCH}" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
  args:
    executable: /bin/bash

- name: Copy docker-compose.yml to VM
  copy:
    src: ../../../../docker-compose.yml
    dest: /opt/docker-compose.yml

- name: Launch Docker Compose services
  shell: "docker-compose -f /opt/docker-compose.yml up -d"
