---
- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Install Docker Compose
  shell: |
    ARCH=$(uname -m)
    OS=$(uname -s)
    curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-${OS}-${ARCH}" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
  args:
    executable: /bin/bash

- name: Ensure /usr/share/confluent-hub-components is writable
  file:
    path: /usr/share/confluent-hub-components
    state: directory
    mode: '0777'

- name: Ensure Kafka plugins directory exists
  file:
    path: /home/flavian_reignault/kafka/plugins
    state: directory
    mode: '0777'

- name: Copy Connector JAR to Kafka plugins directory
  copy:
    src: ../../../../pubsub-group-kafka-connector-1.3.1.jar
    dest: /home/flavian_reignault/kafka/plugins/pubsub-group-kafka-connector-1.3.1.jar

- name: Copy docker-compose.yml to VM
  copy:
    src: ../../../../docker-compose.yml
    dest: /opt/docker-compose.yml

- name: Launch Docker Compose services
  shell: "docker-compose -f /opt/docker-compose.yml up -d"
