apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
  namespace: flink
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flink-taskmanager
  template:
    metadata:
      labels:
        app: flink-taskmanager
    spec:
      containers:
        - name: taskmanager
          image: gcr.io/air-quality-analysis-454417/flink-pyjob:latest
          args: ["taskmanager"]
          ports:
            - containerPort: 6122
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/credentials.json
          volumeMounts:
            - name: gcp-creds
              mountPath: /secrets
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: gcp-creds
          secret:
            secretName: gcp-credentials
      tolerations:
        - key: "node.kubernetes.io/disk-pressure"
          operator: "Exists"
          effect: "NoSchedule"
